# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Brook Luers
tagline:          'Statistician, data scientist
description:      ''
url:              http://www.brookluers.com

author:
  name:           'Brook Luers'

paginate:         5

# Custom vars
version:          2.0.0

#github:
#  repo:           https://github.com/poole/lanyon
