# Site settings
title: Brook Luers
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.brookluers.com" # the base hostname & protocol for your site
github_username:  brookluser

# Build settings
markdown: kramdown
