# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Brook Luers
tagline:          'Statistician, data scientist'
description:      'I am a Ph.D. student in statistics at the University of Michigan.'
url:              http://www.brookluers.com
baseurl: 

# Assets
pages_list:	{'CV':'/cv','Teaching':'/teaching','Research':'/research','Blog':'/blog'}

author:
  name:           'Brook Luers'

paginate:         5

# Custom vars
version:          2.0.0
